### ISSUE TITLE
User Interface for Population Generation

### ISSUE THREAD

**Issue by zeeshan5885** [Qazalbash/jaxtro#8] opened 2023-12-28 15:32 UTC
**Create a .json/.ini file to generate the population for any model.**

- Ask for Mass model
- Ask for Mass model hyperparameters
- Ask for Spin Model
- Ask for the spin model hyperparameter
- Ask for the Redshift model
- Ask for Redshift Hyperparameters (if there are any)
- Ask for an eccentricity model
- Ask for eccentricity hyperparameters
- Ask for a sensitivity
- output directory name
- number of events
- number of rows in each event

Also, please remember that all the parameters generated by each model should be saved in a single .dat file for each event. You can also combine all the events in a single hdf5 file and allow the user to convert them into a .dat file for their use.

**Comment by Qazalbash** [comment] 2023-12-28 19:15
Thanks for pointing this out, but I am closing this issue as a duplicate of #4.

**Closed by Qazalbash** 2023-12-28 19:15 UTC
Labels: duplicate, enhancement
